In [ ]:


def run_length_encode(block):
    """
    Run length encode a block of coefficients.
    
    Parameters
    ----------
    block : numpy array
        The block of coefficients to run length encode.
    
    Returns
    -------
    rle : numpy array
        The run length encoded block.
    """
    # Initialize the run length encoded block
    rle = []
    
    # Initialize the run length
    run_length = 0
    
    # Iterate through the block
    for i in range(block.shape[0]):
        for j in range(block.shape[1]):
            
            # If the current coefficient is not zero
            if block[i][j] != 0:
                
                # Append the run length and coefficient to the run length encoded block
                rle.append(run_length)
                rle.append(block[i][j])
                
                # Reset the run length
                run_length = 0
            
            # If the current coefficient is zero
            else:
                
                # Increment the run length
                run_length += 1
    
    # Append the final run length to the run length encoded block
    rle.append(run_length)
    
    return np.array(rle)

def run_length_decode(rle):
    """
    Run length decode a block of coefficients.
    
    Parameters
    ----------
    rle : numpy array
        The run length encoded block to run length decode.
    
    Returns
    -------
    block : numpy array
        The run length decoded block.
    """
    # Initialize the run length decoded block
    block = np.zeros((8, 8))
    
    # Initialize the index of the run length encoded block
    index = 0
    
    # Iterate through the run length encoded block
    while index < len(rle):
        
        # Get the run length
        run_length = rle[index]
        
        # Increment the index
        index += 1
        
        # Get the coefficient
        coefficient = rle[index]
        
        # Increment the index
        index += 1
        
        # Iterate through the run length
        for i in range(run_length):
            
            # Set the coefficient to zero
            block[int(np.floor(i/8))][i%8] = 0
        
        # Set the coefficient
        block[int(np.floor(run_length/8))][run_length%8] = coefficient
    
    return block

def huffman_encode(block):
    """
    Huffman encode a block of coefficients.
    
    Parameters
    ----------
    block : numpy array
        The block of coefficients to huffman encode.
    
    Returns
    -------
    huffman : numpy array
        The huffman encoded block.
    """
    # Run length encode the block
    rle = run_length_encode(block)
    
    # Initialize the huffman encoded block
    huffman = []
    
    # Iterate through the run length encoded block
    for i in range(len(rle)):
        
        # If the current coefficient is zero
        if rle[i] == 0:
            
            # Append a zero to the huffman encoded block
            huffman.append(0)
        
        # If the current coefficient is not zero
        else:
            
            # Append a one to the huffman encoded block
            huffman.append(1)
            
            # Append the coefficient to the huffman encoded block
            huffman.append(rle[i])
    
    return np.array(huffman)

def huffman_decode(huffman):
    """
    Huffman decode a block of coefficients.
    
    Parameters
    ----------
    huffman : numpy array
        The huffman encoded block to huffman decode.
    
    Returns
    -------
    block : numpy array
        The huffman decoded block.
    """
    # Initialize the huffman decoded block
    block = np.zeros((8, 8))
    
    # Initialize the index of the huffman encoded block
    index = 0
    
    # Iterate through the huffman encoded block
    while index < len(huffman):
        
        # If the current coefficient is zero
        if huffman[index] == 0:
            
            # Increment the index
            index += 1
        
        # If the current coefficient is not zero
        else:
            
            # Increment the index
            index += 1
            
            # Get the coefficient
            coefficient = huffman[index]
            
            # Increment the index
            index += 1
            
            # Iterate through the coefficient
            for i in range(coefficient):
                
                # Set the coefficient to zero
                block[int(np.floor(i/8))][i%8] = 0
            
            # Set the coefficient
            block[int(np.floor(coefficient/8))][coefficient%8] = huffman[index]
            
            # Increment the index
            index += 1
    
    return block

def zigzag_scan(block):
    """
    Zigzag scan a block of coefficients.
    
    Parameters
    ----------
    block : numpy array
        The block of coefficients to zigzag scan.
    
    Returns
    -------
    zigzag : numpy array
        The zigzag scanned block.
    """
    # Initialize the zigzag scanned block
    zigzag = []
    
    # Initialize the zigzag order
    zigzag_order = 8*[0]
    
    # Initialize the index of the zigzag order
    index = 0
    
    # Iterate through the zigzag order
    while index < len(zigzag_order):
        
        # If the current index is even
        if index%2 == 0:
            
            # Set the zigzag order
            zigzag_order[index] = index*(index+1)/2
        
        # If the current index is odd
        else:
            
            # Set the zigzag order
            zigzag_order[index] = (index+1)*(index+2)/2 - 1
        
        # Increment the index
        index += 1
    
    # Iterate through the zigzag order
    for i in range(len(zigzag_order)):
        
        # Append the coefficient to the zigzag scanned block
        zigzag.append(block[int(np.floor(zigzag_order[i]/8))][zigzag_order[i]%8])
    
    return np.array(zigzag)

def zigzag_unscan(zigzag):
    """
    Zigzag unscan a block of coefficients.
    
    Parameters
    ----------
    zigzag : numpy array
        The zigzag scanned block to zigzag unscan.
    
    Returns
    -------
    block : numpy array
        The zigzag unscanned block.
    """
    # Initialize the zigzag unscanned block
    block = np.zeros((8, 8))
    
    # Initialize the zigzag order
    zigzag_order = 8*[0]
    
    # Initialize the index of the zigzag order
    index = 0
    
    # Iterate through the zigzag order
    while index < len(zigzag_order):
        
        # If the current index is even
        if index%2 == 0:
            
            # Set the zigzag order
            zigzag_order[index] = index*(index+1)/2
        
        # If the current index is odd
        else:
            
            # Set the zigzag order
            zigzag_order[index] = (index+1)*(index+2)/2 - 1
        
        # Increment the index
        index += 1
    
    # Iterate through the zigzag order
    for i in range(len(zigzag_order)):
        
        # Set the coefficient
        block[int(np.floor(zigzag_order[i]/8))][zigzag_order[i]%8] = zigzag[i]
    
    return block


quantized_blocks = []
for i in range(dct_blocks.shape[0]):
    quantized_blocks.append(np.round(dct_blocks[i]/quantization_matrix))
quantized_blocks = np.array(quantized_blocks)

# Zigzag scan the quantized DCT coefficients

zigzag_blocks = []
zigzag_order = 8*[0]
for i in range(quantized_blocks.shape[0]):
    zigzag_blocks.append(np.array([quantized_blocks[i][j] for j in zigzag_order]))
zigzag_blocks = np.array(zigzag_blocks)

# Run length encode the zigzag scanned coefficients

rle_blocks = []
for i in range(zigzag_blocks.shape[0]):
    rle_blocks.append(run_length_encode(zigzag_blocks[i]))
rle_blocks = np.array(rle_blocks)

# Huffman encode the run length encoded coefficients

huffman_blocks = []
for i in range(rle_blocks.shape[0]):
    huffman_blocks.append(huffman_encode(rle_blocks[i]))
huffman_blocks = np.array(huffman_blocks)

# Huffman decode the huffman encoded coefficients

huffman_decoded_blocks = []
for i in range(huffman_blocks.shape[0]):
    huffman_decoded_blocks.append(huffman_decode(huffman_blocks[i]))
huffman_decoded_blocks = np.array(huffman_decoded_blocks)

# Run length decode the huffman decoded coefficients

rle_decoded_blocks = []
for i in range(huffman_decoded_blocks.shape[0]):
    rle_decoded_blocks.append(run_length_decode(huffman_decoded_blocks[i]))
rle_decoded_blocks = np.array(rle_decoded_blocks)

# Zigzag unscan the run length decoded coefficients

zigzag_unscanned_blocks = []
for i in range(rle_decoded_blocks.shape[0]):
    zigzag_unscanned_blocks.append(zigzag_unscan(rle_decoded_blocks[i]))
zigzag_unscanned_blocks = np.array(zigzag_unscanned_blocks)

# Inverse quantize the zigzag unscanned coefficients

inverse_quantized_blocks = []
for i in range(zigzag_unscanned_blocks.shape[0]):
    inverse_quantized_blocks.append(zigzag_unscanned_blocks[i]*quantization_matrix)
inverse_quantized_blocks = np.array(inverse_quantized_blocks)

# Apply 2 dimensional inverse DCT to the inverse quantized coefficients

inverse_dct_blocks = []
for i in range(inverse_quantized_blocks.shape[0]):
    inverse_dct_blocks.append(scipy.fftpack.idctn(inverse_quantized_blocks[i], norm='ortho'))
inverse_dct_blocks = np.array(inverse_dct_blocks)

# Add 128 to the inverse DCT coefficients

inverse_dct_blocks = inverse_dct_blocks + 128

# Reconstruct the image from the inverse DCT coefficients

reconstructed_image = np.zeros(image_data.shape)
k = 0
for i in range(0, image_data.shape[0], block_size):
    for j in range(0, image_data.shape[1], block_size):
        reconstructed_image[i:i+block_size, j:j+block_size] = inverse_dct_blocks[k]
        k += 1

# Display the reconstructed image using Matplotlib
plt.imshow(reconstructed_image, cmap='gray')
plt.axis('on')
plt.show()

# Calculate the mean squared error between the original image and the reconstructed image
mse = np.mean((image_data - reconstructed_image)**2)
print("Mean squared error between original image and reconstructed image: {}".format(mse))

# Calculate the peak signal to noise ratio between the original image and the reconstructed image
psnr = 10*np.log10(255**2/mse)
print("Peak signal to noise ratio between original image and reconstructed image: {}".format(psnr))

# Calculate the compression ratio
compression_ratio = (image_data.shape[0]*image_data.shape[1])/(huffman_blocks.shape[0]*huffman_blocks.shape[1])
print("Compression ratio: {}".format(compression_ratio))

# Calculate the bit rate
bit_rate = 8*compression_ratio
print("Bit rate: {}".format(bit_rate))

def calculate_entropy(image):
    """
    Calculate the entropy of an image.
    
    Parameters
    ----------
    image : numpy array
        The image to calculate the entropy of.
    
    Returns
    -------
    entropy : float
        The entropy of the image.
    """
    # Calculate the histogram of the image
    histogram = np.histogram(image, bins=256)[0]
    
    # Calculate the probability of each intensity level
    probability = histogram/np.sum(histogram)
    
    # Calculate the entropy
    entropy = -np.sum([p*np.log2(p) for p in probability if p != 0])
    
    return entropy

# Calculate the entropy of the original image
entropy = calculate_entropy(image_data)
print("Entropy of original image: {}".format(entropy))

# Calculate the entropy of the huffman encoded image
huffman_entropy = calculate_entropy(huffman_blocks)
print("Entropy of huffman encoded image: {}".format(huffman_entropy))

# Calculate the entropy of the huffman decoded image
huffman_decoded_entropy = calculate_entropy(huffman_decoded_blocks)
print("Entropy of huffman decoded image: {}".format(huffman_decoded_entropy))

# Calculate the entropy of the run length encoded image
rle_entropy = calculate_entropy(rle_blocks)
print("Entropy of run length encoded image: {}".format(rle_entropy))

# Calculate the entropy of the run length decoded image
rle_decoded_entropy = calculate_entropy(rle_decoded_blocks)
print("Entropy of run length decoded image: {}".format(rle_decoded_entropy))

# Calculate the entropy of the zigzag scanned image
zigzag_entropy = calculate_entropy(zigzag_blocks)
print("Entropy of zigzag scanned image: {}".format(zigzag_entropy))

# Calculate the entropy of the zigzag unscanned image
zigzag_unscanned_entropy = calculate_entropy(zigzag_unscanned_blocks)
print("Entropy of zigzag unscanned image: {}".format(zigzag_unscanned_entropy))

# Calculate the entropy of the quantized image
quantized_entropy = calculate_entropy(quantized_blocks)
print("Entropy of quantized image: {}".format(quantized_entropy))

# Calculate the entropy of the inverse quantized image
inverse_quantized_entropy = calculate_entropy(inverse_quantized_blocks)
print("Entropy of inverse quantized image: {}".format(inverse_quantized_entropy))

# Calculate the entropy of the DCT image
dct_entropy = calculate_entropy(dct_blocks)
print("Entropy of DCT image: {}".format(dct_entropy))

# Calculate the entropy of the inverse DCT image
inverse_dct_entropy = calculate_entropy(inverse_dct_blocks)
print("Entropy of inverse DCT image: {}".format(inverse_dct_entropy))

# Calculate the entropy of the reconstructed image
reconstructed_image_entropy = calculate_entropy(reconstructed_image)
print("Entropy of reconstructed image: {}".format(reconstructed_image_entropy))

# Calculate the entropy of the original image
original_image_entropy = calculate_entropy(image_data)
print("Entropy of original image: {}".format(original_image_entropy))



In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.fftpack
import scipy.misc
import scipy.signal
import scipy.stats
import scipy.ndimage
import scipy.io


In [3]:
B = np.array([[125,134,137,139,138,138,141,142],
              [113,119,126,134,139,141,144,149],
              [80 ,95 ,103,106,114,127,141,147],
              [63 ,65 ,53 ,62 ,75 ,86 ,108,130],
              [93 ,80 ,60 ,33 ,35 ,35 ,52 ,69 ],
              [126,108,88 ,74 ,53 ,45 ,35 ,35 ],
              [130,116,90 ,96 ,62 ,63 ,55 ,49 ],
              [115,80 ,61 ,65 ,68 ,88 ,68 ,75]])

B = B - 128

print(B)

[[ -3   6   9  11  10  10  13  14]
 [-15  -9  -2   6  11  13  16  21]
 [-48 -33 -25 -22 -14  -1  13  19]
 [-65 -63 -75 -66 -53 -42 -20   2]
 [-35 -48 -68 -95 -93 -93 -76 -59]
 [ -2 -20 -40 -54 -75 -83 -93 -93]
 [  2 -12 -38 -32 -66 -65 -73 -79]
 [-13 -48 -67 -63 -60 -40 -60 -53]]


In [4]:
# apply 2 dimensional DCT to the image

dct = scipy.fftpack.dctn(B, norm='ortho')

print(dct)

[[-272.           16.65692113   47.26840316    3.78600784    6.5
    -0.87458321    0.44504204   -8.58476717]
 [ 182.21994446 -109.12746896  -28.42478751  -24.77660077   -9.25129161
    -6.77210463   -6.32974378   10.42581065]
 [ 117.28675654   19.4243505   -31.15622292   15.94512395    1.52791744
     6.9476639     5.3017767    -8.52280984]
 [ -22.94109838   96.99477478    0.59241359   -7.6911528    -0.52600168
     2.28929172   -2.65361465    2.40110715]
 [ -48.75        -34.77563635   26.55075461    6.84692478    3.75
    -7.06685769    3.344014      4.48154659]
 [  15.73514782   -7.03067964   -8.05855993   -6.63012567   -0.62008333
     3.88317114   -8.44092348   -7.43683591]
 [   0.93767792    0.65520922   -4.9482233     2.90252042   -4.15065878
    -1.12102425    4.90622292    2.53548604]
 [  -4.10828044   10.50639326    5.66154527   -6.79628467   -7.47512023
     1.35297172   -0.91131864    2.43545062]]


In [6]:
# Quantize the DCT coefficients

quantization_matrix = np.array([[16, 11, 10, 16, 24, 40, 51, 61],
                                [12, 12, 14, 19, 26, 58, 60, 55],
                                [14, 13, 16, 24, 40, 57, 69, 56],
                                [14, 17, 22, 29, 51, 87, 80, 62],
                                [18, 22, 37, 56, 68, 109, 103, 77],
                                [24, 35, 55, 64, 81, 104, 113, 92],
                                [49, 64, 78, 87, 103, 121, 120, 101],
                                [72, 92, 95, 98, 112, 100, 103, 99]])

quality_factor = 50

if quality_factor > 50:
    scale = (100 - quality_factor) / 50
    quantization_matrix = quantization_matrix * scale
else:
    scale = quality_factor / 50
    quantization_matrix = quantization_matrix * scale

s = np.zeros((8, 8))

quantized_dct_blocks = []


for i in range(8):
    for j in range(8):
        s[i][j] = round(dct[i][j] / quantization_matrix[i][j])
quantized_dct_blocks.append(s)

quantized_dct_blocks = np.array(quantized_dct_blocks)

print(quantized_dct_blocks.shape)
print(quantized_dct_blocks[0])

(1, 8, 8)
[[-17.   2.   5.   0.   0.   0.   0.   0.]
 [ 15.  -9.  -2.  -1.   0.   0.   0.   0.]
 [  8.   1.  -2.   1.   0.   0.   0.   0.]
 [ -2.   6.   0.   0.   0.   0.   0.   0.]
 [ -3.  -2.   1.   0.   0.   0.   0.   0.]
 [  1.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]]


In [7]:
# perform pointwise multiplication

R = np.multiply(quantized_dct_blocks[0], quantization_matrix)

print(R)

[[-272.   22.   50.    0.    0.    0.    0.    0.]
 [ 180. -108.  -28.  -19.    0.    0.    0.    0.]
 [ 112.   13.  -32.   24.    0.    0.    0.    0.]
 [ -28.  102.    0.    0.    0.    0.    0.    0.]
 [ -54.  -44.   37.    0.    0.    0.    0.    0.]
 [  24.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]]


In [8]:
# Find inverse DCT

inverse_dct = scipy.fftpack.idctn(R, norm='ortho')

print(inverse_dct)

[[  2.71808177   2.12281857   2.2692739    4.26004518   7.64844542
   10.85478565  12.72031507  13.34062081]
 [-18.10339401 -10.6759575   -0.3337261    7.75810677  11.58385593
   12.54958906  12.81399354  13.1153303 ]
 [-43.22936743 -34.5413169  -23.62639162 -15.85524541  -9.79456142
   -0.43167861  12.73430216  23.01408929]
 [-57.98086396 -58.99244546 -63.02831777 -67.87367294 -64.79073904
  -46.46751461 -17.73806742   4.4189307 ]
 [-40.76498095 -50.9610399  -69.26742738 -88.8143355  -98.83797602
  -92.26000513 -73.62023441 -57.69141435]
 [  0.10729541 -12.78053208 -34.04315102 -57.08307516 -76.38046739
  -89.40982651 -96.51536864 -99.39263111]
 [  6.49044019  -8.680524   -28.58657228 -43.20776596 -52.00616591
  -61.15379221 -73.31904728 -83.0164441 ]
 [-25.39418618 -44.56193448 -65.15820365 -70.44241888 -60.82032616
  -50.02665172 -47.88535126 -50.97520989]]


In [9]:
inverse_dct = inverse_dct + 128

print(inverse_dct)

[[130.71808177 130.12281857 130.2692739  132.26004518 135.64844542
  138.85478565 140.72031507 141.34062081]
 [109.89660599 117.3240425  127.6662739  135.75810677 139.58385593
  140.54958906 140.81399354 141.1153303 ]
 [ 84.77063257  93.4586831  104.37360838 112.14475459 118.20543858
  127.56832139 140.73430216 151.01408929]
 [ 70.01913604  69.00755454  64.97168223  60.12632706  63.20926096
   81.53248539 110.26193258 132.4189307 ]
 [ 87.23501905  77.0389601   58.73257262  39.1856645   29.16202398
   35.73999487  54.37976559  70.30858565]
 [128.10729541 115.21946792  93.95684898  70.91692484  51.61953261
   38.59017349  31.48463136  28.60736889]
 [134.49044019 119.319476    99.41342772  84.79223404  75.99383409
   66.84620779  54.68095272  44.9835559 ]
 [102.60581382  83.43806552  62.84179635  57.55758112  67.17967384
   77.97334828  80.11464874  77.02479011]]


In [11]:
error = inverse_dct - (B + 128)

print(error)

[[  5.71808177  -3.87718143  -6.7307261   -6.73995482  -2.35155458
    0.85478565  -0.27968493  -0.65937919]
 [ -3.10339401  -1.6759575    1.6662739    1.75810677   0.58385593
   -0.45041094  -3.18600646  -7.8846697 ]
 [  4.77063257  -1.5413169    1.37360838   6.14475459   4.20543858
    0.56832139  -0.26569784   4.01408929]
 [  7.01913604   4.00755454  11.97168223  -1.87367294 -11.79073904
   -4.46751461   2.26193258   2.4189307 ]
 [ -5.76498095  -2.9610399   -1.26742738   6.1856645   -5.83797602
    0.73999487   2.37976559   1.30858565]
 [  2.10729541   7.21946792   5.95684898  -3.08307516  -1.38046739
   -6.40982651  -3.51536864  -6.39263111]
 [  4.49044019   3.319476     9.41342772 -11.20776596  13.99383409
    3.84620779  -0.31904728  -4.0164441 ]
 [-12.39418618   3.43806552   1.84179635  -7.44241888  -0.82032616
  -10.02665172  12.11464874   2.02479011]]


In [13]:
# Load the .mat file into a dictionary
mat_data = scipy.io.loadmat('SampleImages/camera256.mat')

# Extract the image data from the dictionary
image_data = mat_data['camera256']
block_size = 8
blocks = []
for i in range(0, image_data.shape[0], block_size):
    for j in range(0, image_data.shape[1], block_size):
        blocks.append(image_data[i:i+block_size, j:j+block_size])

# Convert blocks to numpy array
blocks = np.array(blocks)

print(blocks.shape)
print(image_data.shape)
print(blocks[0])
print(image_data[0:8, 0:8])

(1024, 8, 8)
(256, 256)
[[156 159 158 155 158 156 159 158]
 [160 154 157 158 157 159 158 158]
 [156 159 158 155 158 156 159 158]
 [160 154 157 158 157 159 158 158]
 [156 153 155 159 159 155 156 155]
 [155 155 155 157 156 159 152 158]
 [156 153 157 156 153 155 154 155]
 [159 159 156 158 156 159 157 161]]
[[156 159 158 155 158 156 159 158]
 [160 154 157 158 157 159 158 158]
 [156 159 158 155 158 156 159 158]
 [160 154 157 158 157 159 158 158]
 [156 153 155 159 159 155 156 155]
 [155 155 155 157 156 159 152 158]
 [156 153 157 156 153 155 154 155]
 [159 159 156 158 156 159 157 161]]


In [18]:
import numpy as np

# Assuming 'blocks' is a 3D numpy array with shape (1024, 8, 8)
num_blocks = int(np.sqrt(blocks.shape[0]))
block_size = blocks.shape[1]

# Reshape the blocks array
blocks_reshaped = blocks.reshape((num_blocks, num_blocks, block_size, block_size))

# Initialize an empty image
reconstructed_image = np.zeros((num_blocks * block_size, num_blocks * block_size))

# Reconstruct the image from blocks
for i in range(num_blocks):
    for j in range(num_blocks):
        reconstructed_image[i*block_size:(i+1)*block_size, j*block_size:(j+1)*block_size] = blocks_reshaped[i, j, :, :]

# Now, 'reconstructed_image' should contain your original 256x256 image


# chage the components to integers
reconstructed_image = reconstructed_image.astype(int)
print(reconstructed_image.shape)
print(reconstructed_image[0:8, 0:8])

(256, 256)
[[156 159 158 155 158 156 159 158]
 [160 154 157 158 157 159 158 158]
 [156 159 158 155 158 156 159 158]
 [160 154 157 158 157 159 158 158]
 [156 153 155 159 159 155 156 155]
 [155 155 155 157 156 159 152 158]
 [156 153 157 156 153 155 154 155]
 [159 159 156 158 156 159 157 161]]
